import { Teacher, Classroom, CalendarData } from './types';

export const maestros: Teacher[] = [
  {
    id: '1',
    nombre: 'Dr. Roberto Sánchez',
    departamento: 'Matemáticas',
    materias: ['Cálculo Diferencial e Integral', 'Álgebra Lineal', 'Ecuaciones Diferenciales'],
    disponible: false,
    horasAsignadas: 18,
    horasMaximas: 18,
    email: 'roberto.sanchez@udlap.mx',
    telefono: '222-229-2000 ext. 1234',
    especialidad: 'Matemáticas Aplicadas',
  },
  {
    id: '2',
    nombre: 'Mtra. Ana García',
    departamento: 'Ciencias de la Computación',
    materias: ['Programación Orientada a Objetos', 'Estructuras de Datos', 'Algoritmos'],
    disponible: false,
    horasAsignadas: 16,
    horasMaximas: 18,
    email: 'ana.garcia@udlap.mx',
    telefono: '222-229-2000 ext. 2345',
    especialidad: 'Ingeniería de Software',
  },
  {
    id: '3',
    nombre: 'Dr. Carlos Mendoza',
    departamento: 'Humanidades',
    materias: ['Historia de México', 'Historia Universal', 'Filosofía Moderna'],
    disponible: true,
    horasAsignadas: 9,
    horasMaximas: 18,
    email: 'carlos.mendoza@udlap.mx',
    telefono: '222-229-2000 ext. 3456',
    especialidad: 'Historia Latinoamericana',
  },
  {
    id: '4',
    nombre: 'Mtro. Jorge Ramírez',
    departamento: 'Negocios',
    materias: ['Contabilidad Financiera', 'Auditoría', 'Análisis Financiero'],
    disponible: true,
    horasAsignadas: 6,
    horasMaximas: 18,
    email: 'jorge.ramirez@udlap.mx',
    telefono: '222-229-2000 ext. 4567',
    especialidad: 'Finanzas Corporativas',
  },
  {
    id: '5',
    nombre: 'Dra. Patricia López',
    departamento: 'Ciencias Naturales',
    materias: ['Química General', 'Química Orgánica', 'Bioquímica'],
    disponible: false,
    horasAsignadas: 15,
    horasMaximas: 18,
    email: 'patricia.lopez@udlap.mx',
    telefono: '222-229-2000 ext. 5678',
    especialidad: 'Química Analítica',
  },
  {
    id: '6',
    nombre: 'Mtra. Laura Hernández',
    departamento: 'Comunicación',
    materias: ['Comunicación Oral y Escrita', 'Redacción Profesional', 'Periodismo'],
    disponible: false,
    horasAsignadas: 12,
    horasMaximas: 18,
    email: 'laura.hernandez@udlap.mx',
    telefono: '222-229-2000 ext. 6789',
    especialidad: 'Comunicación Estratégica',
  },
  {
    id: '7',
    nombre: 'Dr. Miguel Torres',
    departamento: 'Ciencias de la Computación',
    materias: ['Bases de Datos', 'Desarrollo Web', 'Arquitectura de Software'],
    disponible: true,
    horasAsignadas: 9,
    horasMaximas: 18,
    email: 'miguel.torres@udlap.mx',
    telefono: '222-229-2000 ext. 7890',
    especialidad: 'Sistemas de Información',
  },
  {
    id: '8',
    nombre: 'Dr. Fernando Ruiz',
    departamento: 'Economía',
    materias: ['Microeconomía', 'Macroeconomía', 'Economía Internacional'],
    disponible: true,
    horasAsignadas: 0,
    horasMaximas: 18,
    email: 'fernando.ruiz@udlap.mx',
    telefono: '222-229-2000 ext. 8901',
    especialidad: 'Teoría Económica',
  },
  {
    id: '9',
    nombre: 'Mtra. Sofia Martínez',
    departamento: 'Psicología',
    materias: ['Psicología General', 'Psicología Social', 'Desarrollo Humano'],
    disponible: true,
    horasAsignadas: 6,
    horasMaximas: 18,
    email: 'sofia.martinez@udlap.mx',
    telefono: '222-229-2000 ext. 9012',
    especialidad: 'Psicología Clínica',
  },
  {
    id: '10',
    nombre: 'Dr. Ricardo Flores',
    departamento: 'Ingeniería',
    materias: ['Física I', 'Física II', 'Mecánica de Materiales'],
    disponible: true,
    horasAsignadas: 12,
    horasMaximas: 18,
    email: 'ricardo.flores@udlap.mx',
    telefono: '222-229-2000 ext. 0123',
    especialidad: 'Física Aplicada',
  },
];

export const salones: Classroom[] = [
  {
    id: '1',
    nombre: 'LA-101',
    edificio: 'Laboratorio A',
    capacidad: 30,
    ocupacion: 28,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: false,
  },
  {
    id: '2',
    nombre: 'AU-205',
    edificio: 'Auditorio',
    capacidad: 120,
    ocupacion: 85,
    equipamiento: ['Proyector', 'Sistema de audio', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '3',
    nombre: 'BI-303',
    edificio: 'Biblioteca',
    capacidad: 45,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Pizarrón interactivo', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '4',
    nombre: 'C-102',
    edificio: 'Ciencia',
    capacidad: 35,
    ocupacion: 32,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: false,
  },
  {
    id: '5',
    nombre: 'HU-201',
    edificio: 'Humanidades',
    capacidad: 40,
    ocupacion: 25,
    equipamiento: ['Proyector', 'Aire acondicionado', 'Sistema de audio'],
    disponible: true,
  },
  {
    id: '6',
    nombre: 'IN-104',
    edificio: 'Ingeniería',
    capacidad: 50,
    ocupacion: 48,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado', 'Pizarrón interactivo'],
    disponible: false,
  },
  {
    id: '7',
    nombre: 'NE-305',
    edificio: 'Negocios',
    capacidad: 38,
    ocupacion: 20,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '8',
    nombre: 'LA-203',
    edificio: 'Laboratorio A',
    capacidad: 25,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  // Salones CG
  {
    id: '9',
    nombre: 'CG-201',
    edificio: 'Ciencias y Gestión',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  // Salones CI
  {
    id: '10',
    nombre: 'CI-203',
    edificio: 'Ciencias de la Información',
    capacidad: 28,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  // Salones CN
  {
    id: '11',
    nombre: 'CN-108',
    edificio: 'Ciencias Naturales',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '12',
    nombre: 'CN-109',
    edificio: 'Ciencias Naturales',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '13',
    nombre: 'CN-110',
    edificio: 'Ciencias Naturales',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '14',
    nombre: 'CN-122',
    edificio: 'Ciencias Naturales',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '15',
    nombre: 'CN-124',
    edificio: 'Ciencias Naturales',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '16',
    nombre: 'CN-201',
    edificio: 'Ciencias Naturales',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '17',
    nombre: 'CN-220',
    edificio: 'Ciencias Naturales',
    capacidad: 38,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '18',
    nombre: 'CN-221',
    edificio: 'Ciencias Naturales',
    capacidad: 38,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '19',
    nombre: 'CN-223',
    edificio: 'Ciencias Naturales',
    capacidad: 38,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '20',
    nombre: 'CN-235',
    edificio: 'Ciencias Naturales',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '21',
    nombre: 'CN-237',
    edificio: 'Ciencias Naturales',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  // Salones CS
  {
    id: '22',
    nombre: 'CS-101',
    edificio: 'Ciencias Sociales',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '23',
    nombre: 'CS-102',
    edificio: 'Ciencias Sociales',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '24',
    nombre: 'CS-104',
    edificio: 'Ciencias Sociales',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '25',
    nombre: 'CS-105',
    edificio: 'Ciencias Sociales',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '26',
    nombre: 'CS-106',
    edificio: 'Ciencias Sociales',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '27',
    nombre: 'CS-107',
    edificio: 'Ciencias Sociales',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '28',
    nombre: 'CS-108',
    edificio: 'Ciencias Sociales',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '29',
    nombre: 'CS-109',
    edificio: 'Ciencias Sociales',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '30',
    nombre: 'CS-110',
    edificio: 'Ciencias Sociales',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '31',
    nombre: 'CS-111',
    edificio: 'Ciencias Sociales',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '32',
    nombre: 'CS-112',
    edificio: 'Ciencias Sociales',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '33',
    nombre: 'CS-113',
    edificio: 'Ciencias Sociales',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '34',
    nombre: 'CS-116',
    edificio: 'Ciencias Sociales',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '35',
    nombre: 'CS-117',
    edificio: 'Ciencias Sociales',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '36',
    nombre: 'CS-118',
    edificio: 'Ciencias Sociales',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '37',
    nombre: 'CS-119',
    edificio: 'Ciencias Sociales',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '38',
    nombre: 'CS-120',
    edificio: 'Ciencias Sociales',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '39',
    nombre: 'CS-121',
    edificio: 'Ciencias Sociales',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '40',
    nombre: 'CS-122',
    edificio: 'Ciencias Sociales',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '41',
    nombre: 'CS-123',
    edificio: 'Ciencias Sociales',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  // Más salones HU
  {
    id: '42',
    nombre: 'HU-105',
    edificio: 'Humanidades',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '43',
    nombre: 'HU-106',
    edificio: 'Humanidades',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '44',
    nombre: 'HU-108',
    edificio: 'Humanidades',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '45',
    nombre: 'HU-109',
    edificio: 'Humanidades',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '46',
    nombre: 'HU-112',
    edificio: 'Humanidades',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '47',
    nombre: 'HU-113',
    edificio: 'Humanidades',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '48',
    nombre: 'HU-114',
    edificio: 'Humanidades',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '49',
    nombre: 'HU-117',
    edificio: 'Humanidades',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '50',
    nombre: 'HU-204',
    edificio: 'Humanidades',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '51',
    nombre: 'HU-204A',
    edificio: 'Humanidades',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '52',
    nombre: 'HU-205',
    edificio: 'Humanidades',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '53',
    nombre: 'HU-206',
    edificio: 'Humanidades',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '54',
    nombre: 'HU-207',
    edificio: 'Humanidades',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '55',
    nombre: 'HU-212',
    edificio: 'Humanidades',
    capacidad: 38,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '56',
    nombre: 'HU-213',
    edificio: 'Humanidades',
    capacidad: 38,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '57',
    nombre: 'HU-304',
    edificio: 'Humanidades',
    capacidad: 45,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '58',
    nombre: 'HU-307',
    edificio: 'Humanidades',
    capacidad: 45,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '59',
    nombre: 'HU-313',
    edificio: 'Humanidades',
    capacidad: 45,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '60',
    nombre: 'HU-322',
    edificio: 'Humanidades',
    capacidad: 48,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '61',
    nombre: 'HU-404',
    edificio: 'Humanidades',
    capacidad: 50,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '62',
    nombre: 'HU-405',
    edificio: 'Humanidades',
    capacidad: 50,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '63',
    nombre: 'HU-414',
    edificio: 'Humanidades',
    capacidad: 50,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '64',
    nombre: 'HU-415',
    edificio: 'Humanidades',
    capacidad: 50,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  // Salones IA (Ingeniería Automotriz o Ingeniería Aplicada)
  {
    id: '65',
    nombre: 'IA-101',
    edificio: 'Ingeniería Aplicada',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '66',
    nombre: 'IA-104',
    edificio: 'Ingeniería Aplicada',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '67',
    nombre: 'IA-108',
    edificio: 'Ingeniería Aplicada',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '68',
    nombre: 'IA-109',
    edificio: 'Ingeniería Aplicada',
    capacidad: 32,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '69',
    nombre: 'IA-120',
    edificio: 'Ingeniería Aplicada',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '70',
    nombre: 'IA-121',
    edificio: 'Ingeniería Aplicada',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '71',
    nombre: 'IA-122',
    edificio: 'Ingeniería Aplicada',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '72',
    nombre: 'IA-204',
    edificio: 'Ingeniería Aplicada',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '73',
    nombre: 'IA-205',
    edificio: 'Ingeniería Aplicada',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '74',
    nombre: 'IA-206',
    edificio: 'Ingeniería Aplicada',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '75',
    nombre: 'IA-209',
    edificio: 'Ingeniería Aplicada',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '76',
    nombre: 'IA-210',
    edificio: 'Ingeniería Aplicada',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '77',
    nombre: 'IA-211',
    edificio: 'Ingeniería Aplicada',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '78',
    nombre: 'IA-212',
    edificio: 'Ingeniería Aplicada',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '79',
    nombre: 'IA-213',
    edificio: 'Ingeniería Aplicada',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '80',
    nombre: 'IA-214',
    edificio: 'Ingeniería Aplicada',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '81',
    nombre: 'IA-215',
    edificio: 'Ingeniería Aplicada',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  // Más salones LA
  {
    id: '82',
    nombre: 'LA-205',
    edificio: 'Laboratorio A',
    capacidad: 25,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '83',
    nombre: 'LA-206',
    edificio: 'Laboratorio A',
    capacidad: 25,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '84',
    nombre: 'LA-207',
    edificio: 'Laboratorio A',
    capacidad: 25,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado'],
    disponible: true,
  },
  // Salones LD (Laboratorio Digital o similar)
  {
    id: '85',
    nombre: 'LD-100',
    edificio: 'Laboratorio Digital',
    capacidad: 20,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado', 'Pizarrón interactivo'],
    disponible: true,
  },
  {
    id: '86',
    nombre: 'LD-200',
    edificio: 'Laboratorio Digital',
    capacidad: 20,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado', 'Pizarrón interactivo'],
    disponible: true,
  },
  {
    id: '87',
    nombre: 'LD-1001',
    edificio: 'Laboratorio Digital',
    capacidad: 20,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado', 'Pizarrón interactivo'],
    disponible: true,
  },
  {
    id: '88',
    nombre: 'LD-1002',
    edificio: 'Laboratorio Digital',
    capacidad: 20,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Computadoras', 'Aire acondicionado', 'Pizarrón interactivo'],
    disponible: true,
  },
  // Más salones NE
  {
    id: '89',
    nombre: 'NE-104',
    edificio: 'Negocios',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '90',
    nombre: 'NE-105',
    edificio: 'Negocios',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '91',
    nombre: 'NE-106',
    edificio: 'Negocios',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '92',
    nombre: 'NE-107',
    edificio: 'Negocios',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '93',
    nombre: 'NE-109',
    edificio: 'Negocios',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '94',
    nombre: 'NE-110',
    edificio: 'Negocios',
    capacidad: 38,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '95',
    nombre: 'NE-111',
    edificio: 'Negocios',
    capacidad: 38,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '96',
    nombre: 'NE-112',
    edificio: 'Negocios',
    capacidad: 38,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '97',
    nombre: 'NE-202',
    edificio: 'Negocios',
    capacidad: 40,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  // Salones SL (Salones Libres o similar)
  {
    id: '98',
    nombre: 'SL-202',
    edificio: 'Salones Libres',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '99',
    nombre: 'SL-203',
    edificio: 'Salones Libres',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '100',
    nombre: 'SL-206',
    edificio: 'Salones Libres',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '101',
    nombre: 'SL-207',
    edificio: 'Salones Libres',
    capacidad: 30,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '102',
    nombre: 'SL-307',
    edificio: 'Salones Libres',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  {
    id: '103',
    nombre: 'SL-308',
    edificio: 'Salones Libres',
    capacidad: 35,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Aire acondicionado'],
    disponible: true,
  },
  // Salón ZR
  {
    id: '104',
    nombre: 'ZR-43',
    edificio: 'Zona Recreativa',
    capacidad: 25,
    ocupacion: 0,
    equipamiento: ['Proyector', 'Sistema de audio', 'Aire acondicionado'],
    disponible: true,
  },
];

// Calendarios por salón
export const calendariosPorSalon: Record<string, CalendarData> = {
  'LA-101': {
    eventos: [
      {
        id: '1',
        titulo: 'Programación Orientada a Objetos',
        maestro: 'Mtra. Ana García',
        dia: 'Lunes',
        horaInicio: '07:00',
        horaFin: '08:30',
        color: 'bg-blue-100 border-blue-300 text-blue-900',
      },
      {
        id: '2',
        titulo: 'Programación Orientada a Objetos',
        maestro: 'Mtra. Ana García',
        dia: 'Miércoles',
        horaInicio: '07:00',
        horaFin: '08:30',
        color: 'bg-blue-100 border-blue-300 text-blue-900',
      },
      {
        id: '3',
        titulo: 'Estructuras de Datos',
        maestro: 'Mtra. Ana García',
        dia: 'Martes',
        horaInicio: '10:00',
        horaFin: '11:30',
        color: 'bg-green-100 border-green-300 text-green-900',
      },
      {
        id: '4',
        titulo: 'Estructuras de Datos',
        maestro: 'Mtra. Ana García',
        dia: 'Jueves',
        horaInicio: '10:00',
        horaFin: '11:30',
        color: 'bg-green-100 border-green-300 text-green-900',
      },
    ],
  },
  'C-102': {
    eventos: [
      {
        id: '1',
        titulo: 'Química Orgánica',
        maestro: 'Dra. Patricia López',
        dia: 'Lunes',
        horaInicio: '08:30',
        horaFin: '10:00',
        color: 'bg-purple-100 border-purple-300 text-purple-900',
      },
      {
        id: '2',
        titulo: 'Química Orgánica',
        maestro: 'Dra. Patricia López',
        dia: 'Miércoles',
        horaInicio: '08:30',
        horaFin: '10:00',
        color: 'bg-purple-100 border-purple-300 text-purple-900',
      },
      {
        id: '3',
        titulo: 'Química General',
        maestro: 'Dra. Patricia López',
        dia: 'Martes',
        horaInicio: '14:00',
        horaFin: '15:30',
        color: 'bg-pink-100 border-pink-300 text-pink-900',
      },
      {
        id: '4',
        titulo: 'Química General',
        maestro: 'Dra. Patricia López',
        dia: 'Jueves',
        horaInicio: '14:00',
        horaFin: '15:30',
        color: 'bg-pink-100 border-pink-300 text-pink-900',
      },
    ],
  },
  'HU-201': {
    eventos: [
      {
        id: '1',
        titulo: 'Historia de México',
        maestro: 'Dr. Carlos Mendoza',
        dia: 'Lunes',
        horaInicio: '10:00',
        horaFin: '11:30',
        color: 'bg-yellow-100 border-yellow-300 text-yellow-900',
      },
      {
        id: '2',
        titulo: 'Historia de México',
        maestro: 'Dr. Carlos Mendoza',
        dia: 'Miércoles',
        horaInicio: '10:00',
        horaFin: '11:30',
        color: 'bg-yellow-100 border-yellow-300 text-yellow-900',
      },
      {
        id: '3',
        titulo: 'Historia Universal',
        maestro: 'Dr. Carlos Mendoza',
        dia: 'Martes',
        horaInicio: '08:30',
        horaFin: '10:00',
        color: 'bg-orange-100 border-orange-300 text-orange-900',
      },
      {
        id: '4',
        titulo: 'Historia Universal',
        maestro: 'Dr. Carlos Mendoza',
        dia: 'Jueves',
        horaInicio: '08:30',
        horaFin: '10:00',
        color: 'bg-orange-100 border-orange-300 text-orange-900',
      },
    ],
  },
  'IN-104': {
    eventos: [
      {
        id: '1',
        titulo: 'Cálculo Diferencial e Integral',
        maestro: 'Dr. Roberto Sánchez',
        dia: 'Lunes',
        horaInicio: '07:00',
        horaFin: '08:30',
        color: 'bg-red-100 border-red-300 text-red-900',
      },
      {
        id: '2',
        titulo: 'Cálculo Diferencial e Integral',
        maestro: 'Dr. Roberto Sánchez',
        dia: 'Miércoles',
        horaInicio: '07:00',
        horaFin: '08:30',
        color: 'bg-red-100 border-red-300 text-red-900',
      },
      {
        id: '3',
        titulo: 'Álgebra Lineal',
        maestro: 'Dr. Roberto Sánchez',
        dia: 'Martes',
        horaInicio: '10:00',
        horaFin: '11:30',
        color: 'bg-indigo-100 border-indigo-300 text-indigo-900',
      },
      {
        id: '4',
        titulo: 'Álgebra Lineal',
        maestro: 'Dr. Roberto Sánchez',
        dia: 'Jueves',
        horaInicio: '10:00',
        horaFin: '11:30',
        color: 'bg-indigo-100 border-indigo-300 text-indigo-900',
      },
      {
        id: '5',
        titulo: 'Ecuaciones Diferenciales',
        maestro: 'Dr. Roberto Sánchez',
        dia: 'Viernes',
        horaInicio: '08:30',
        horaFin: '10:00',
        color: 'bg-teal-100 border-teal-300 text-teal-900',
      },
      {
        id: '6',
        titulo: 'Ecuaciones Diferenciales',
        maestro: 'Dr. Roberto Sánchez',
        dia: 'Viernes',
        horaInicio: '10:00',
        horaFin: '11:30',
        color: 'bg-teal-100 border-teal-300 text-teal-900',
      },
    ],
  },
  'NE-305': {
    eventos: [
      {
        id: '1',
        titulo: 'Contabilidad Financiera',
        maestro: 'Mtro. Jorge Ramírez',
        dia: 'Martes',
        horaInicio: '14:00',
        horaFin: '15:30',
        color: 'bg-cyan-100 border-cyan-300 text-cyan-900',
      },
      {
        id: '2',
        titulo: 'Contabilidad Financiera',
        maestro: 'Mtro. Jorge Ramírez',
        dia: 'Jueves',
        horaInicio: '14:00',
        horaFin: '15:30',
        color: 'bg-cyan-100 border-cyan-300 text-cyan-900',
      },
    ],
  },
};

// Materias disponibles
export const materiasDisponibles = [
  {
    id: '1',
    nombre: 'Cálculo Diferencial e Integral',
    departamento: 'Matemáticas',
    creditos: 8,
    maestros: ['Dr. Roberto Sánchez'],
  },
  {
    id: '2',
    nombre: 'Álgebra Lineal',
    departamento: 'Matemáticas',
    creditos: 6,
    maestros: ['Dr. Roberto Sánchez'],
  },
  {
    id: '3',
    nombre: 'Ecuaciones Diferenciales',
    departamento: 'Matemáticas',
    creditos: 6,
    maestros: ['Dr. Roberto Sánchez'],
  },
  {
    id: '4',
    nombre: 'Programación Orientada a Objetos',
    departamento: 'Ciencias de la Computación',
    creditos: 8,
    maestros: ['Mtra. Ana García'],
  },
  {
    id: '5',
    nombre: 'Estructuras de Datos',
    departamento: 'Ciencias de la Computación',
    creditos: 8,
    maestros: ['Mtra. Ana García'],
  },
  {
    id: '6',
    nombre: 'Algoritmos',
    departamento: 'Ciencias de la Computación',
    creditos: 6,
    maestros: ['Mtra. Ana García'],
  },
  {
    id: '7',
    nombre: 'Historia de México',
    departamento: 'Humanidades',
    creditos: 6,
    maestros: ['Dr. Carlos Mendoza'],
  },
  {
    id: '8',
    nombre: 'Historia Universal',
    departamento: 'Humanidades',
    creditos: 6,
    maestros: ['Dr. Carlos Mendoza'],
  },
  {
    id: '9',
    nombre: 'Filosofía Moderna',
    departamento: 'Humanidades',
    creditos: 6,
    maestros: ['Dr. Carlos Mendoza'],
  },
  {
    id: '10',
    nombre: 'Contabilidad Financiera',
    departamento: 'Negocios',
    creditos: 8,
    maestros: ['Mtro. Jorge Ramírez'],
  },
  {
    id: '11',
    nombre: 'Auditoría',
    departamento: 'Negocios',
    creditos: 6,
    maestros: ['Mtro. Jorge Ramírez'],
  },
  {
    id: '12',
    nombre: 'Análisis Financiero',
    departamento: 'Negocios',
    creditos: 6,
    maestros: ['Mtro. Jorge Ramírez'],
  },
  {
    id: '13',
    nombre: 'Química General',
    departamento: 'Ciencias Naturales',
    creditos: 8,
    maestros: ['Dra. Patricia López'],
  },
  {
    id: '14',
    nombre: 'Química Orgánica',
    departamento: 'Ciencias Naturales',
    creditos: 8,
    maestros: ['Dra. Patricia López'],
  },
  {
    id: '15',
    nombre: 'Bioquímica',
    departamento: 'Ciencias Naturales',
    creditos: 6,
    maestros: ['Dra. Patricia López'],
  },
  {
    id: '16',
    nombre: 'Comunicación Oral y Escrita',
    departamento: 'Comunicación',
    creditos: 6,
    maestros: ['Mtra. Laura Hernández'],
  },
  {
    id: '17',
    nombre: 'Redacción Profesional',
    departamento: 'Comunicación',
    creditos: 6,
    maestros: ['Mtra. Laura Hernández'],
  },
  {
    id: '18',
    nombre: 'Periodismo',
    departamento: 'Comunicación',
    creditos: 6,
    maestros: ['Mtra. Laura Hernández'],
  },
  {
    id: '19',
    nombre: 'Bases de Datos',
    departamento: 'Ciencias de la Computación',
    creditos: 8,
    maestros: ['Dr. Miguel Torres'],
  },
  {
    id: '20',
    nombre: 'Desarrollo Web',
    departamento: 'Ciencias de la Computación',
    creditos: 6,
    maestros: ['Dr. Miguel Torres'],
  },
  {
    id: '21',
    nombre: 'Arquitectura de Software',
    departamento: 'Ciencias de la Computación',
    creditos: 6,
    maestros: ['Dr. Miguel Torres'],
  },
  {
    id: '22',
    nombre: 'Microeconomía',
    departamento: 'Economía',
    creditos: 6,
    maestros: ['Dr. Fernando Ruiz'],
  },
  {
    id: '23',
    nombre: 'Macroeconomía',
    departamento: 'Economía',
    creditos: 6,
    maestros: ['Dr. Fernando Ruiz'],
  },
  {
    id: '24',
    nombre: 'Economía Internacional',
    departamento: 'Economía',
    creditos: 6,
    maestros: ['Dr. Fernando Ruiz'],
  },
  {
    id: '25',
    nombre: 'Psicología General',
    departamento: 'Psicología',
    creditos: 6,
    maestros: ['Mtra. Sofia Martínez'],
  },
  {
    id: '26',
    nombre: 'Psicología Social',
    departamento: 'Psicología',
    creditos: 6,
    maestros: ['Mtra. Sofia Martínez'],
  },
  {
    id: '27',
    nombre: 'Desarrollo Humano',
    departamento: 'Psicología',
    creditos: 6,
    maestros: ['Mtra. Sofia Martínez'],
  },
  {
    id: '28',
    nombre: 'Física I',
    departamento: 'Ingeniería',
    creditos: 8,
    maestros: ['Dr. Ricardo Flores'],
  },
  {
    id: '29',
    nombre: 'Física II',
    departamento: 'Ingeniería',
    creditos: 8,
    maestros: ['Dr. Ricardo Flores'],
  },
  {
    id: '30',
    nombre: 'Mecánica de Materiales',
    departamento: 'Ingeniería',
    creditos: 6,
    maestros: ['Dr. Ricardo Flores'],
  },
];