-- Base de datos SQL para las aulas del proyecto
-- Tabla pensada para PostgreSQL, MySQL y SQLite con tipos simples.

BEGIN TRANSACTION;

DROP TABLE IF EXISTS aulas;

CREATE TABLE aulas (
  id INTEGER PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  edificio TEXT NOT NULL,
  capacidad INTEGER NOT NULL,
  ocupacion INTEGER NOT NULL DEFAULT 0,
  equipamiento TEXT NOT NULL,
  disponible INTEGER NOT NULL DEFAULT 1 CHECK (disponible IN (0, 1))
);

CREATE INDEX idx_aulas_edificio ON aulas (edificio);
CREATE INDEX idx_aulas_capacidad ON aulas (capacidad);
CREATE INDEX idx_aulas_disponible ON aulas (disponible);

INSERT INTO aulas (id, nombre, edificio, capacidad, ocupacion, equipamiento, disponible) VALUES
  (1, 'LA-101', 'Laboratorio A', 30, 28, 'Proyector, Computadoras, Aire acondicionado', 0),
  (2, 'AU-205', 'Auditorio', 120, 85, 'Proyector, Sistema de audio, Aire acondicionado', 1),
  (3, 'BI-303', 'Biblioteca', 45, 0, 'Proyector, Pizarrón interactivo, Aire acondicionado', 1),
  (4, 'C-102', 'Ciencia', 35, 32, 'Proyector, Aire acondicionado', 0),
  (5, 'HU-201', 'Humanidades', 40, 25, 'Proyector, Aire acondicionado, Sistema de audio', 1),
  (6, 'IN-104', 'Ingeniería', 50, 48, 'Proyector, Computadoras, Aire acondicionado, Pizarrón interactivo', 0),
  (7, 'NE-305', 'Negocios', 38, 20, 'Proyector, Aire acondicionado', 1),
  (8, 'LA-203', 'Laboratorio A', 25, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (9, 'CG-201', 'Ciencias y Gestión', 30, 0, 'Proyector, Aire acondicionado', 1),
  (10, 'CI-203', 'Ciencias de la Información', 28, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (11, 'CN-108', 'Ciencias Naturales', 32, 0, 'Proyector, Aire acondicionado', 1),
  (12, 'CN-109', 'Ciencias Naturales', 32, 0, 'Proyector, Aire acondicionado', 1),
  (13, 'CN-110', 'Ciencias Naturales', 32, 0, 'Proyector, Aire acondicionado', 1),
  (14, 'CN-122', 'Ciencias Naturales', 35, 0, 'Proyector, Aire acondicionado', 1),
  (15, 'CN-124', 'Ciencias Naturales', 35, 0, 'Proyector, Aire acondicionado', 1),
  (16, 'CN-201', 'Ciencias Naturales', 40, 0, 'Proyector, Aire acondicionado', 1),
  (17, 'CN-220', 'Ciencias Naturales', 38, 0, 'Proyector, Aire acondicionado', 1),
  (18, 'CN-221', 'Ciencias Naturales', 38, 0, 'Proyector, Aire acondicionado', 1),
  (19, 'CN-223', 'Ciencias Naturales', 38, 0, 'Proyector, Aire acondicionado', 1),
  (20, 'CN-235', 'Ciencias Naturales', 40, 0, 'Proyector, Aire acondicionado', 1),
  (21, 'CN-237', 'Ciencias Naturales', 40, 0, 'Proyector, Aire acondicionado', 1),
  (22, 'CS-101', 'Ciencias Sociales', 30, 0, 'Proyector, Aire acondicionado', 1),
  (23, 'CS-102', 'Ciencias Sociales', 30, 0, 'Proyector, Aire acondicionado', 1),
  (24, 'CS-104', 'Ciencias Sociales', 30, 0, 'Proyector, Aire acondicionado', 1),
  (25, 'CS-105', 'Ciencias Sociales', 30, 0, 'Proyector, Aire acondicionado', 1),
  (26, 'CS-106', 'Ciencias Sociales', 30, 0, 'Proyector, Aire acondicionado', 1),
  (27, 'CS-107', 'Ciencias Sociales', 30, 0, 'Proyector, Aire acondicionado', 1),
  (28, 'CS-108', 'Ciencias Sociales', 30, 0, 'Proyector, Aire acondicionado', 1),
  (29, 'CS-109', 'Ciencias Sociales', 30, 0, 'Proyector, Aire acondicionado', 1),
  (30, 'CS-110', 'Ciencias Sociales', 32, 0, 'Proyector, Aire acondicionado', 1),
  (31, 'CS-111', 'Ciencias Sociales', 32, 0, 'Proyector, Aire acondicionado', 1),
  (32, 'CS-112', 'Ciencias Sociales', 32, 0, 'Proyector, Aire acondicionado', 1),
  (33, 'CS-113', 'Ciencias Sociales', 32, 0, 'Proyector, Aire acondicionado', 1),
  (34, 'CS-116', 'Ciencias Sociales', 35, 0, 'Proyector, Aire acondicionado', 1),
  (35, 'CS-117', 'Ciencias Sociales', 35, 0, 'Proyector, Aire acondicionado', 1),
  (36, 'CS-118', 'Ciencias Sociales', 35, 0, 'Proyector, Aire acondicionado', 1),
  (37, 'CS-119', 'Ciencias Sociales', 35, 0, 'Proyector, Aire acondicionado', 1),
  (38, 'CS-120', 'Ciencias Sociales', 35, 0, 'Proyector, Aire acondicionado', 1),
  (39, 'CS-121', 'Ciencias Sociales', 35, 0, 'Proyector, Aire acondicionado', 1),
  (40, 'CS-122', 'Ciencias Sociales', 35, 0, 'Proyector, Aire acondicionado', 1),
  (41, 'CS-123', 'Ciencias Sociales', 35, 0, 'Proyector, Aire acondicionado', 1),
  (42, 'HU-105', 'Humanidades', 30, 0, 'Proyector, Aire acondicionado', 1),
  (43, 'HU-106', 'Humanidades', 30, 0, 'Proyector, Aire acondicionado', 1),
  (44, 'HU-108', 'Humanidades', 30, 0, 'Proyector, Aire acondicionado', 1),
  (45, 'HU-109', 'Humanidades', 30, 0, 'Proyector, Aire acondicionado', 1),
  (46, 'HU-112', 'Humanidades', 32, 0, 'Proyector, Aire acondicionado', 1),
  (47, 'HU-113', 'Humanidades', 32, 0, 'Proyector, Aire acondicionado', 1),
  (48, 'HU-114', 'Humanidades', 32, 0, 'Proyector, Aire acondicionado', 1),
  (49, 'HU-117', 'Humanidades', 35, 0, 'Proyector, Aire acondicionado', 1),
  (50, 'HU-204', 'Humanidades', 40, 0, 'Proyector, Aire acondicionado', 1),
  (51, 'HU-204A', 'Humanidades', 40, 0, 'Proyector, Aire acondicionado', 1),
  (52, 'HU-205', 'Humanidades', 40, 0, 'Proyector, Aire acondicionado', 1),
  (53, 'HU-206', 'Humanidades', 40, 0, 'Proyector, Aire acondicionado', 1),
  (54, 'HU-207', 'Humanidades', 40, 0, 'Proyector, Aire acondicionado', 1),
  (55, 'HU-212', 'Humanidades', 38, 0, 'Proyector, Aire acondicionado', 1),
  (56, 'HU-213', 'Humanidades', 38, 0, 'Proyector, Aire acondicionado', 1),
  (57, 'HU-304', 'Humanidades', 45, 0, 'Proyector, Aire acondicionado', 1),
  (58, 'HU-307', 'Humanidades', 45, 0, 'Proyector, Aire acondicionado', 1),
  (59, 'HU-313', 'Humanidades', 45, 0, 'Proyector, Aire acondicionado', 1),
  (60, 'HU-322', 'Humanidades', 48, 0, 'Proyector, Aire acondicionado', 1),
  (61, 'HU-404', 'Humanidades', 50, 0, 'Proyector, Aire acondicionado', 1),
  (62, 'HU-405', 'Humanidades', 50, 0, 'Proyector, Aire acondicionado', 1),
  (63, 'HU-414', 'Humanidades', 50, 0, 'Proyector, Aire acondicionado', 1),
  (64, 'HU-415', 'Humanidades', 50, 0, 'Proyector, Aire acondicionado', 1),
  (65, 'IA-101', 'Ingeniería Aplicada', 30, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (66, 'IA-104', 'Ingeniería Aplicada', 30, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (67, 'IA-108', 'Ingeniería Aplicada', 32, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (68, 'IA-109', 'Ingeniería Aplicada', 32, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (69, 'IA-120', 'Ingeniería Aplicada', 35, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (70, 'IA-121', 'Ingeniería Aplicada', 35, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (71, 'IA-122', 'Ingeniería Aplicada', 35, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (72, 'IA-204', 'Ingeniería Aplicada', 40, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (73, 'IA-205', 'Ingeniería Aplicada', 40, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (74, 'IA-206', 'Ingeniería Aplicada', 40, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (75, 'IA-209', 'Ingeniería Aplicada', 40, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (76, 'IA-210', 'Ingeniería Aplicada', 40, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (77, 'IA-211', 'Ingeniería Aplicada', 40, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (78, 'IA-212', 'Ingeniería Aplicada', 40, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (79, 'IA-213', 'Ingeniería Aplicada', 40, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (80, 'IA-214', 'Ingeniería Aplicada', 40, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (81, 'IA-215', 'Ingeniería Aplicada', 40, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (82, 'LA-205', 'Laboratorio A', 25, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (83, 'LA-206', 'Laboratorio A', 25, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (84, 'LA-207', 'Laboratorio A', 25, 0, 'Proyector, Computadoras, Aire acondicionado', 1),
  (85, 'LD-100', 'Laboratorio Digital', 20, 0, 'Proyector, Computadoras, Aire acondicionado, Pizarrón interactivo', 1),
  (86, 'LD-200', 'Laboratorio Digital', 20, 0, 'Proyector, Computadoras, Aire acondicionado, Pizarrón interactivo', 1),
  (87, 'LD-1001', 'Laboratorio Digital', 20, 0, 'Proyector, Computadoras, Aire acondicionado, Pizarrón interactivo', 1),
  (88, 'LD-1002', 'Laboratorio Digital', 20, 0, 'Proyector, Computadoras, Aire acondicionado, Pizarrón interactivo', 1),
  (89, 'NE-104', 'Negocios', 35, 0, 'Proyector, Aire acondicionado', 1),
  (90, 'NE-105', 'Negocios', 35, 0, 'Proyector, Aire acondicionado', 1),
  (91, 'NE-106', 'Negocios', 35, 0, 'Proyector, Aire acondicionado', 1),
  (92, 'NE-107', 'Negocios', 35, 0, 'Proyector, Aire acondicionado', 1),
  (93, 'NE-109', 'Negocios', 35, 0, 'Proyector, Aire acondicionado', 1),
  (94, 'NE-110', 'Negocios', 38, 0, 'Proyector, Aire acondicionado', 1),
  (95, 'NE-111', 'Negocios', 38, 0, 'Proyector, Aire acondicionado', 1),
  (96, 'NE-112', 'Negocios', 38, 0, 'Proyector, Aire acondicionado', 1),
  (97, 'NE-202', 'Negocios', 40, 0, 'Proyector, Aire acondicionado', 1),
  (98, 'SL-202', 'Salones Libres', 30, 0, 'Proyector, Aire acondicionado', 1),
  (99, 'SL-203', 'Salones Libres', 30, 0, 'Proyector, Aire acondicionado', 1),
  (100, 'SL-206', 'Salones Libres', 30, 0, 'Proyector, Aire acondicionado', 1),
  (101, 'SL-207', 'Salones Libres', 30, 0, 'Proyector, Aire acondicionado', 1),
  (102, 'SL-307', 'Salones Libres', 35, 0, 'Proyector, Aire acondicionado', 1),
  (103, 'SL-308', 'Salones Libres', 35, 0, 'Proyector, Aire acondicionado', 1),
  (104, 'ZR-43', 'Zona Recreativa', 25, 0, 'Proyector, Sistema de audio, Aire acondicionado', 1);

COMMIT;
